using System;
using System.Linq;
using io.github.ykysnk.CheatClientProtector;
using io.github.ykysnk.LogManager;
using io.github.ykysnk.utils;
using io.github.ykysnk.utils.Extensions;
using JetBrains.Annotations;
using UnityEngine;
using UnityEngine.Serialization;
using VRC.SDKBase;
using VRC.Udon.Common.Interfaces;
using Object = UnityEngine.Object;

namespace io.github.ykysnk.WorldBasic.Udon
{
#if !COMPILER_UDONSHARP && UNITY_EDITOR
    public abstract partial class BasicUdonSharpBehaviour : ILogManager
    {
        public LogManager.LogManager LogManager
        {
            get => logManager;
            set => logManager = value;
        }

        [ContextMenu("Force reset ID")]
        public void ResetId()
        {
            if (Utils.IsInPrefab()) return;
            guid = Guid.NewGuid().ToString();
            Log("Setting new ID on object: " + gameObject.FullName(), gameObject);
        }

        public static bool IsUnique(string id) =>
            FindObjectsOfType<BasicUdonSharpBehaviour>(true).Count(x => x.guid == id) == 1;

        private void UpdateOrResetID()
        {
            if (Utils.IsInPrefab()) return;
            if (string.IsNullOrEmpty(guid) || !IsUnique(guid))
                ResetId();
        }
    }
#endif

    [PublicAPI]
    public abstract partial class BasicUdonSharpBehaviour : CheatClientProtectorBehaviour
    {
        private const string IsTurnOnKey = "isTurnOn";
        private const string ModeKey = "mode";

        [FormerlySerializedAs("id")] [SerializeField] [UniqueID]
        private string guid;

        [HideInInspector] public PlayerGuid playerGuid;
        [HideInInspector] public LogManager.LogManager logManager;
        [SerializeField] [HideInInspector] private string logName;
        [SerializeField] [Range(1, 256)] private float loopFreamRate = 60;

        /// <summary>
        ///     Indicates whether the full name of the object should be included in log messages generated by this instance of
        ///     <see cref="BasicUdonSharpBehaviour" />.
        /// </summary>
        /// <remarks>
        ///     This property determines if detailed object identification, such as its fully qualified name, is appended to log
        ///     outputs.
        ///     It is primarily used to enhance clarity and traceability in logs, particularly during debugging or complex
        ///     behaviors
        ///     within the Unity environment.
        /// </remarks>
        [Header("Log Settings")] [SerializeField]
        protected bool logShowFullName = true;

        /// <summary>
        ///     Gets the color code used for log name display in the log output.
        /// </summary>
        /// <remarks>
        ///     This property defines the color of the log name as a string in hexadecimal format (e.g., "#D771C0").
        ///     It is primarily used to visually differentiate logs by applying the specified color to the log name
        ///     in outputs such as Unity's console or custom logging systems.
        /// </remarks>
        [SerializeField] [ColorHex] protected string logNameColor = "#D771C0";

        /// <summary>
        ///     Gets the unique identifier associated with the current instance of the <see cref="BasicUdonSharpBehaviour" />.
        /// </summary>
        /// <remarks>
        ///     This property provides a read-only string value that uniquely identifies the instance.
        ///     It is typically used to distinguish between different instances and for serialization purposes in save operations.
        /// </remarks>
        public string ID => guid;

        /// <summary>
        ///     Gets the GUID (Globally Unique Identifier) associated with the local player.
        /// </summary>
        /// <remarks>
        ///     The property provides a string representation of the GUID for the local player, using
        ///     the associated <see cref="PlayerGuid" /> instance. If the <see cref="PlayerGuid" /> instance is valid,
        ///     the value is generated using the player's RandomKey. Otherwise, a default empty GUID
        ///     (defined as "00000000-0000-0000-0000-000000000000") is returned.
        /// </remarks>
        [NotNull]
        protected string LocalPlayerGuid =>
            Utilities.IsValid(playerGuid)
                ? playerGuid.GetLocalPlayerGuid(playerGuid.RandomKey)
                : PlayerGuid.EmptyGuid;

        /// <summary>
        ///     Invoked by Unity to validate the component's configuration and ensure
        ///     proper initialization of fields or dependencies during editing.
        /// </summary>
        /// <remarks>
        ///     <b>Please use <see cref="OnChange" /> instead.</b>
        /// </remarks>
        [Obsolete("Use OnChange instead.", true)]
        protected virtual void OnValidate()
        {
#if !COMPILER_UDONSHARP && UNITY_EDITOR
            logName = GetType().Name;
            UpdateOrResetID();
#endif
            OnChange();
        }

        protected virtual void OnChange()
        {
        }

        protected void StartFreamRateLoop() => FreamRateLoopInternal();

        public void FreamRateLoopInternal()
        {
            FreamRateLoop();
            SendCustomEventDelayedSeconds(nameof(FreamRateLoopInternal), Mathf.Max(0.01f, 1f / loopFreamRate));
        }

        protected virtual void FreamRateLoop()
        {
        }

        private string LogPrefix()
        {
            var msg = $"[<color={logNameColor}>{logName}</color>] ";
            if (logShowFullName)
                msg += $"({gameObject.FullName()}) ";
            return msg;
        }

        private string LogPrefix([NotNull] GameObject obj) =>
            $"[<color={logNameColor}>{logName}</color>] ({obj.FullName()}) ";

        private void AddLogToManager([CanBeNull] object message, LogType logType)
        {
            if (!Utilities.IsValid(logManager) || !Utils.IsPlaying()) return;

            var tempMsg = message != null ? message.ToString() : "null";

            if (logShowFullName)
                tempMsg = $"({gameObject.FullName()}) " + tempMsg;

            logManager.AddLog(logNameColor, logName, tempMsg, logType, logManager.RandomKey);
        }

        private void AddLogToManager([NotNull] GameObject obj, [CanBeNull] object message, LogType logType)
        {
            if (!Utilities.IsValid(logManager) || !Utils.IsPlaying()) return;

            var tempMsg = message != null ? message.ToString() : "null";

            if (logShowFullName)
                tempMsg = $"({obj.FullName()}) " + tempMsg;

            logManager.AddLog(logNameColor, logName, tempMsg, logType, logManager.RandomKey);
        }

        /// <summary>
        ///     Logs a message with the default log type and displays it in the console.
        /// </summary>
        /// <param name="message">The message to log.</param>
        protected void Log([CanBeNull] object message)
        {
            Debug.Log(LogPrefix() + message, this);
            AddLogToManager(message, LogType.Log);
        }

        /// <summary>
        ///     Logs a warning message with a specific prefix, displays it in the console,
        ///     and adds it to the log manager with a warning log type.
        /// </summary>
        /// <param name="message">The warning message to log.</param>
        protected void LogWarning([CanBeNull] object message)
        {
            Debug.LogWarning(LogPrefix() + message, this);
            AddLogToManager(message, LogType.Warning);
        }

        /// <summary>
        ///     Logs an error message with additional context and adds it to the log manager.
        /// </summary>
        /// <param name="message">The error message to log.</param>
        protected void LogError([CanBeNull] object message)
        {
            Debug.LogError(LogPrefix() + message, this);
            AddLogToManager(message, LogType.Error);
        }

        /// <summary>
        ///     Logs a message with the specified context, prepending a custom log prefix and routing the log to the manager.
        /// </summary>
        /// <param name="message">The message to log.</param>
        /// <param name="context">The context object to associate with the log.</param>
        protected void Log([CanBeNull] object message, [NotNull] Object context)
        {
            Debug.Log(LogPrefix() + message, context);
            AddLogToManager(message, LogType.Log);
        }

        /// <summary>
        ///     Logs a warning message with the specified object and context. The warning is displayed in the console and added to
        ///     the log manager.
        /// </summary>
        /// <param name="message">The warning message to log.</param>
        /// <param name="context">
        ///     The UnityEngine.Object context to associate with the log, typically used for identifying the
        ///     source object.
        /// </param>
        protected void LogWarning([CanBeNull] object message, [NotNull] Object context)
        {
            Debug.LogWarning(LogPrefix() + message, context);
            AddLogToManager(message, LogType.Warning);
        }

        /// <summary>
        ///     Logs an error message and associates it with a context object.
        /// </summary>
        /// <param name="message">The error message to log.</param>
        /// <param name="context">The context object to associate with the error log.</param>
        protected void LogError([CanBeNull] object message, [NotNull] Object context)
        {
            Debug.LogError(LogPrefix() + message, context);
            AddLogToManager(message, LogType.Error);
        }

        /// <summary>
        ///     Logs a message with a prefix that includes the object's name and color-coded log name.
        /// </summary>
        /// <param name="obj">The GameObject associated with the log message.</param>
        /// <param name="message">The message to be logged.</param>
        protected void Log([NotNull] GameObject obj, [CanBeNull] object message)
        {
            Debug.Log(LogPrefix(obj) + message, this);
            AddLogToManager(message, LogType.Log);
        }

        /// <summary>
        ///     Logs a warning message with a specified prefix and adds it to the log manager.
        /// </summary>
        /// <param name="obj">The GameObject associated with the log message.</param>
        /// <param name="message">The message content to log as a warning.</param>
        protected void LogWarning([NotNull] GameObject obj, [CanBeNull] object message)
        {
            Debug.LogWarning(LogPrefix(obj) + message, this);
            AddLogToManager(message, LogType.Warning);
        }

        /// <summary>
        ///     Logs an error message with a specified game object context and adds it to the log manager.
        /// </summary>
        /// <param name="obj">The game object associated with the error message.</param>
        /// <param name="message">The error message to log.</param>
        protected void LogError([NotNull] GameObject obj, [CanBeNull] object message)
        {
            Debug.LogError(LogPrefix(obj) + message, this);
            AddLogToManager(message, LogType.Error);
        }

        /// <summary>
        ///     Logs a message with the default log type, an associated GameObject, and a specified context.
        /// </summary>
        /// <param name="obj">The GameObject to associate with the log message.</param>
        /// <param name="message">The message to log.</param>
        /// <param name="context">The context object to include with the log message.</param>
        protected void Log([NotNull] GameObject obj, [CanBeNull] object message, [NotNull] Object context)
        {
            Debug.Log(LogPrefix(obj) + message, context);
            AddLogToManager(obj, message, LogType.Log);
        }

        /// <summary>
        ///     Logs a warning message associated with a specific game object.
        /// </summary>
        /// <param name="obj">The game object related to the warning message.</param>
        /// <param name="message">The warning message to log.</param>
        /// <param name="context">An object to associate with the log message, used to provide context in the console.</param>
        protected void LogWarning([NotNull] GameObject obj, [CanBeNull] object message, [NotNull] Object context)
        {
            Debug.LogWarning(LogPrefix(obj) + message, context);
            AddLogToManager(obj, message, LogType.Warning);
        }

        /// <summary>
        ///     Logs an error message associated with a specific GameObject and provides additional context information.
        /// </summary>
        /// <param name="obj">The GameObject associated with the error message.</param>
        /// <param name="message">The error message to log.</param>
        /// <param name="context">An optional context object related to the error, used to identify the source of the log message.</param>
        protected void LogError([NotNull] GameObject obj, [CanBeNull] object message, [NotNull] Object context)
        {
            Debug.LogError(LogPrefix(obj) + message, context);
            AddLogToManager(obj, message, LogType.Error);
        }

        /// <summary>
        ///     Give a unique key for save data
        /// </summary>
        /// <param name="key">The keyword</param>
        /// <returns></returns>
        protected string SaveKey(string key) => $"{ID}_{key}";

        /// <summary>
        ///     Give an is turn-on unique key for save data
        /// </summary>
        /// <returns></returns>
        protected string SaveIsTurnOn() => SaveKey(IsTurnOnKey);

        /// <summary>
        ///     Give a mode unique key for save data
        /// </summary>
        /// <returns></returns>
        protected string SaveMode() => SaveKey(ModeKey);

        /// <summary>
        ///     Give a unique key for save data
        /// </summary>
        /// <param name="obj">The BasicUdonSharpBehaviour</param>
        /// <param name="key">The keyword</param>
        /// <returns></returns>
        protected static string SaveKey([NotNull] BasicUdonSharpBehaviour obj, [NotNull] string key) => $"{obj.ID}_{key}";

        /// <summary>
        ///     Give an is turn-on unique key for save data
        /// </summary>
        /// <param name="obj">The BasicUdonSharpBehaviour</param>
        /// <returns></returns>
        protected static string SaveIsTurnOn([NotNull] BasicUdonSharpBehaviour obj) => SaveKey(obj, IsTurnOnKey);

        /// <summary>
        ///     Give a mode unique key for save data
        /// </summary>
        /// <param name="obj">The BasicUdonSharpBehaviour</param>
        /// <returns></returns>
        protected static string SaveMode([NotNull] BasicUdonSharpBehaviour obj) => SaveKey(obj, ModeKey);

        /// <summary>
        ///     Check if the player is the first master
        /// </summary>
        /// <param name="player">The player</param>
        /// <returns>true if the player is first master</returns>
        protected bool IsFirstMaster([NotNull] VRCPlayerApi player)
        {
            if (Utilities.IsValid(playerGuid)) return playerGuid.IsFirstMaster(player, playerGuid.RandomKey);
            LogWarning("playerGuid has not been valid.");
            return player.isMaster;
        }

        /// <summary>
        ///     Virtual save method
        /// </summary>
        /// <param name="player">The player</param>
        protected virtual void Save([NotNull] VRCPlayerApi player)
        {
        }

        /// <summary>
        ///     Alias method of <see cref="Save(VRCPlayerApi)" />
        /// </summary>
        protected void Save() => Save(Networking.LocalPlayer);

        /// <summary>
        ///     Virtual load method
        /// </summary>
        /// <param name="player">The player</param>
        protected virtual void Load([NotNull] VRCPlayerApi player)
        {
        }

        /// <summary>
        ///     Alias method of <see cref="Load(VRCPlayerApi)" />
        /// </summary>
        protected void Load() => Load(Networking.LocalPlayer);

        // Refs: https://github.com/purabesan/ManualSyncUB/blob/main/sources/ManualSyncUB.cs
        /* 同期関連処理のまとめ */

        /// <summary>
        ///     オーナ権限取得
        /// </summary>
        /// <param name="target">取得対象オブジェクト</param>
        protected void GetOwner([CanBeNull] GameObject target = null)
        {
            if (!Utilities.IsValid(target))
                target = gameObject;
            if (!Networking.IsOwner(target))
                Networking.SetOwner(Networking.LocalPlayer, target);
        }

        // 同期変数受信時の処理
        public override void OnDeserialization() => AfterSynchronize(false);

        /// <summary>
        ///     同期化処理。オーナ権限の移動・同期指示側のAfterSynchronize実行を含む。
        /// </summary>
        /// <param name="localOnly">
        ///     If set to true, limits the synchronization process to the local scope,
        ///     preventing network-wide updates.
        /// </param>
        protected void Synchronize(bool localOnly = false)
        {
            GetOwner();
            if (!localOnly)
                RequestSerialization();
            AfterSynchronize(true);
        }

        /// <summary>
        ///     同期後の共通処理
        /// </summary>
        /// <param name="isOwner">
        ///     A boolean value indicating whether the current player is the owner of the object after synchronization.
        /// </param>
        protected virtual void AfterSynchronize(bool isOwner)
        {
        }

        /// <summary>
        ///     グローバル処理実行。SendCustomNetworkEvent Allするだけ。
        /// </summary>
        /// <param name="eventName">実行したいpublic関数。nameof(関数名)にて指定</param>
        protected void ExecuteOnAll(string eventName) => SendCustomNetworkEvent(NetworkEventTarget.All, eventName);
    }
}